# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreadorPlantilla.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CreadorPlantilla(object):
    def setupUi(self, CreadorPlantilla):
        CreadorPlantilla.setObjectName("CreadorPlantilla")
        CreadorPlantilla.resize(786, 275)
        self.centralwidget = QtWidgets.QWidget(CreadorPlantilla)
        self.centralwidget.setObjectName("centralwidget")
        self.Boton_Seleccionar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Seleccionar.setGeometry(QtCore.QRect(10, 10, 141, 23))
        self.Boton_Seleccionar.setObjectName("Boton_Seleccionar")
        self.Seleccion = QtWidgets.QLabel(self.centralwidget)
        self.Seleccion.setGeometry(QtCore.QRect(180, 10, 591, 21))
        self.Seleccion.setFrameShape(QtWidgets.QFrame.Panel)
        self.Seleccion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Seleccion.setText("")
        self.Seleccion.setObjectName("Seleccion")
        self.NumCarpetas = QtWidgets.QLabel(self.centralwidget)
        self.NumCarpetas.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.NumCarpetas.setObjectName("NumCarpetas")
        self.carpetas = QtWidgets.QSpinBox(self.centralwidget)
        self.carpetas.setGeometry(QtCore.QRect(150, 50, 42, 22))
        self.carpetas.setObjectName("carpetas")
        self.Boton_Ejecutar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Ejecutar.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.Boton_Ejecutar.setObjectName("Boton_Ejecutar")
        self.NumSubCarpetas = QtWidgets.QLabel(self.centralwidget)
        self.NumSubCarpetas.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.NumSubCarpetas.setObjectName("NumSubCarpetas")
        self.subcarpetas = QtWidgets.QSpinBox(self.centralwidget)
        self.subcarpetas.setGeometry(QtCore.QRect(150, 90, 42, 22))
        self.subcarpetas.setObjectName("subcarpetas")
        self.aviso_error = QtWidgets.QLabel(self.centralwidget)
        self.aviso_error.setGeometry(QtCore.QRect(140, 210, 601, 21))
        self.aviso_error.setText("")
        self.aviso_error.setObjectName("aviso_error")
        CreadorPlantilla.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreadorPlantilla)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        self.menuSalir = QtWidgets.QMenu(self.menubar)
        self.menuSalir.setObjectName("menuSalir")
        CreadorPlantilla.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreadorPlantilla)
        self.statusbar.setObjectName("statusbar")
        CreadorPlantilla.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(CreadorPlantilla)
        self.actionSalir.setObjectName("actionSalir")
        self.menuSalir.addAction(self.actionSalir)
        self.menubar.addAction(self.menuSalir.menuAction())

        self.retranslateUi(CreadorPlantilla)
        QtCore.QMetaObject.connectSlotsByName(CreadorPlantilla)

    def retranslateUi(self, CreadorPlantilla):
        _translate = QtCore.QCoreApplication.translate
        CreadorPlantilla.setWindowTitle(_translate("CreadorPlantilla", "Creador Carpetas"))
        self.Boton_Seleccionar.setText(_translate("CreadorPlantilla", "Seleccionar Archivo"))
        self.NumCarpetas.setText(_translate("CreadorPlantilla", "Numero de carpetas"))
        self.Boton_Ejecutar.setText(_translate("CreadorPlantilla", "Ejecutar"))
        self.NumSubCarpetas.setText(_translate("CreadorPlantilla", "Numero de Subcarpetas"))
        self.menuSalir.setTitle(_translate("CreadorPlantilla", "Salir"))
        self.actionSalir.setText(_translate("CreadorPlantilla", "Salir"))
        self.actionSalir.setShortcut(_translate("CreadorPlantilla", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreadorPlantilla = QtWidgets.QMainWindow()
    ui = CreadorPlantilla()
    ui.setupUi(CreadorPlantilla)
    CreadorPlantilla.show()
    sys.exit(app.exec_())
